# For more information on GitHub Actions for Azure, refer to https://github.com/Azure/Actions
# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:

    # checkout the repo
    - uses: actions/checkout@master
    
    # Maven Build and package
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    # build and clean
    - name: maven build, clean
      run: |
        mvn clean install

    # Azure login
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} # Define secret variable in repository settings as per action documentation
   
    # deploy web app using publish profile credentials
    - uses: azure/webapps-deploy@v1
      with: 
        app-name: SpringVueTest  # Replace with your app name
        package: '${{ github.workspace }}/target/*.war'

    # Azure logout 
    - name: logout
      run: |
        az logout
